# Generated by Django 5.2.5 on 2025-08-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='Todo',
        ),
    ]
